import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Top Courses - Codehelp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://top-course-finder.netlify.app/logo192.png" type="image/x-icon" />
        {/* You can also include other meta tags here */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
